name: Unit Test
run-name: GitHub Actions Implementation
on: [push]
jobs:
  GitHub-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm test